/**
    Utility that parses the gdextension_interface JSON and generates
    a D file with the core interface.
*/
module app;
import generator;
import std.stdio;
import std.file;
import commandr;
import std.process;
import std.path;

int main(string[] args) {
    auto app = new Program("gde-gen", "1.0")
        .summary("Generator for DLang GDExtension bindings.")
        .author("Luna the Foxgirl")
        .add(new Option("g", "godot", "Path to the godot executable to use").defaultValue("godot"))
        .add(new Option("d", "dir", "Root directory to work in.").defaultValue("."))
        .add(new Flag("f", "force", "Force regenerate the bindings."))
        .parse(args);

    if (app.flag("force") || !exists("gde.lock")) {
        JSONValue[2] jsonIn;
        try {
            jsonIn = parseGDEJson(app.option("godot"));
        } catch(ErrnoException ex) {
            stderr.writeln(ex.msg);
            return ex.errno;
        }

        // Make lock
        std.file.write("gde.lock", "");

        writefln("Generating bindings for %s...", jsonIn[GDE_API]["header"]["version_full_name"].str);
        jsonIn.writeVariantSizeInfo(app.option("dir"));
        jsonIn.writeGDEInterface(app.option("dir"));
    }
    return 0;
}

/**
    Writes the variant size info file.

    Params:
        jsonIn =    The JSON Input
        dir =       Root directory to write the file in.
*/
void writeVariantSizeInfo(JSONValue[2] jsonIn, string dir) {
    auto target = new GDEBindingWriter(buildPath(dir, "source/godot/core/gdextension/variant_size.d"));
    target.writeHeader(DDOC(
        "Variant Size Info", 
        "This file is automatically generated; do not modify it."),
        "godot.core.gdextension.variant_size"
    );
    target.writeImport("godot.core.gdextension.iface");
    target.writenls();

    auto api = jsonIn[GDE_API];
    int written = 0;
    string precision = api["header"]["precision"].str;
    foreach(classSize; api["builtin_class_sizes"].array) {
        string buildConfig = classSize["build_configuration"].str;

        switch(precision) {
            case "single":
                if (buildConfig == "float_32" || buildConfig == "float_64") {
                    if (written > 0)
                        target.write(" else ");
                    
                    target.beginVersionBlock(buildConfig == "float_32" ? "D_X32" : "D_LP64");
                    target.writeBuiltinSizes(classSize);
                    target.endBlock(false);

                    written++;
                }
                break;

            case "double":
                if (buildConfig == "double_32" || buildConfig == "double_64") {
                    if (written > 0)
                        target.write(" else ");
                    
                    target.beginVersionBlock(buildConfig == "double_32" ? "D_X32" : "D_LP64");
                    target.writeBuiltinSizes(classSize);
                    target.endBlock(false);

                    written++;
                }
                break;
            
            default:
                break;
        }
    }
    target.flush();
}

/**
    Writes variant size enums to the wrriter.

    Params:
        writer =    The writer to write to.
        list =      The JSON list of builtin class sizes.
*/
void writeBuiltinSizes(GDEBindingWriter writer, JSONValue list) {
    import std.string : toUpper;
    foreach(size; list["sizes"].array) {
        writer.writefln("enum VARIANT_SIZE_%s = %s;", toUpper(size["name"].str), size["size"].toString());
    }
}

/**
    Writes the GDExtension interface file.

    Params:
        jsonIn =    The JSON Input
        dir =       Root directory to write the file in.
*/
void writeGDEInterface(JSONValue[2] jsonIn, string dir) {
    auto target = new GDEBindingWriter(buildPath(dir, "source/godot/core/gdextension/iface.d"));
    target.writeHeader(DDOC(
        "GDExtension Interface", 
        "This file implements the GDExtension interface.\n\nThis file is automatically generated; do not modify it."),
        "godot.core.gdextension.iface"
    );
    target.writeImport("core.stdc.stdint");
    target.writeImport("core.stdc.stddef");
    target.writenls();
    target.writeAlias("char16_t", "wchar");
    target.writeAlias("char32_t", "dchar");
    target.writenls();
    target.writeln("extern(C) @nogc nothrow:");

    GDEType[] ifaceTypes = parseTypes(jsonIn[GDE_INTERFACE], GDE_INTERFACE);
    foreach(type; ifaceTypes) {
        target.writeType(type);
    }
    target.flush();
}